<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" />
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
    <PackageReference Include="Mapster" />
    <PackageReference Include="MediatR" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Caching.Hybrid" />
    <PackageReference Include="Microsoft.Extensions.Localization" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Centerix.Domain\Centerix.Domain.csproj" />
  </ItemGroup>



</Project>
